insert into GL_BALSTMD (statdate
                        , stattype
                        , hostsystem
                        , fcccustnum
                        , fccaccount
                        , fccbranch
                        , ext_custid
                        , accbrn
                        , cbaccount
                        , acctype
                        , currcode
                        , sqnumber
                        , createdate
                        , timecreate
                        , openblnca
                        , closeblnca
                        , dbdocnt
                        , dbturnovra
                        , crdocnt
                        , crturnovra
                        , openblncn
                        , closeblncn
                        , dbturnovrn
                        , crturnovrn
                        , rate
                        , inbdate
                        , outbdate
                        , rcustname
                        , custinn
                        , ecustname
                        , cstaddrsw1
                        , cstaddrsw2
                        , cstaddrsw3
                        , cstaddrsw4
                        , cstaddrkl
                        , cstaddrkf
                        , bcustbic
                        , rbankname
                        , ebankname
                        , bcstcorrac
                        , bcustswift
                        , bcustinn
                        , ed
                        , branch_id
                        , alt_ac_no
                        , accname
                        , acodname
                        , currname
                        , dateunload
                        , lstoperdat)
select              statdate
                    , stattype
                    , hostsystem
                    , fcccustnum
                    , fccaccount
                    , fccbranch
                    , ext_custid
                    , accbrn
                    , cbaccount
                    , acctype
                    , currcode
                    , sqnumber
                    , createdate
                    , timecreate
                    , openblnca
                    , closeblnca
                    , dbdocnt
                    , dbturnovra
                    , crdocnt
                    , crturnovra
                    , openblncn
                    , closeblncn
                    , dbturnovrn
                    , crturnovrn
                    , rate
                    , inbdate
                    , outbdate
                    , rcustname
                    , custinn
                    , ecustname
                    , cstaddrsw1
                    , cstaddrsw2
                    , cstaddrsw3
                    , cstaddrsw4
                    , cstaddrkl
                    , cstaddrkf
                    , bcustbic
                    , rbankname
                    , ebankname
                    , bcstcorrac
                    , bcustswift
                    , bcustinn
                    , ed
                    , branch_id
                    , alt_ac_no
                    , accname
                    , acodname
                    , currname
                    , dateunload
                    , lstoperdat from TMP_GL_BALSTMD