INSERT INTO SESSION.GLVD_BAL_SUBSTEP1
  SELECT DISTINCT
    C.DAT       CDAT,
    B.DAT       BDAT,
    B.ACID,
    B.BSAACID,
    D.ID,
    B.OBAC      OBAL,
    B.DTAC      DTRN,
    B.CTAC      CTRN,
    BEG.CURDATE UNLOAD_DAT,
    B.OBBC      OBALRUR,
    B.DTBC      DTRNRUR,
    B.CTBC      CTRNRUR
  FROM BALTUR B, CAL C,
    (SELECT
       BSAACID,
       ID
     FROM GL_ACC
     WHERE DTC IS NULL AND ACCTYPE IN (SELECT ACCTYPE
                                       FROM GL_BALACC)) D,
    (SELECT
       MAX(C.DAT)      AS VBEGDATE,
       MAX(OD.CURDATE) AS CURDATE
     FROM CAL C
       , (SELECT VALUE(?, DATE('2029-01-01')) CURDATE
          FROM SYSIBM.SYSDUMMY1) OD
     WHERE C.DAT < OD.CURDATE AND C.HOL <> 'X' AND C.CCY = 'RUR'
    ) BEG
  WHERE B.BSAACID = D.BSAACID
        AND B.DAT >= BEG.VBEGDATE
        AND C.DAT BETWEEN B.DAT AND B.DATTO
        AND C.DAT BETWEEN BEG.VBEGDATE AND BEG.CURDATE AND C.CCY = 'RUR' AND C.HOL <> 'X'
        AND NOT EXISTS(SELECT 1
                       FROM GLVD_BAL GBAL
                       WHERE GBAL.BSAACID = B.BSAACID AND GBAL.DAT = C.DAT)

