insert into PST (ID,POD,VALD,ACID,BSAACID,CCY,AMNT,AMNTBC,PBR,PDRF,CPDRF,INVISIBLE,FINALETRS,PNAR,CTYPE,PCID,PREF,DPMT,FLEX_EVENT_CODE,
                 RNARLNG,RNARSHT,OREF,DOCN,OREF_SRC,OPERATOR,OPER_DEPT,AUTHORIZER,AUTH_DEPT,GLO_REF,EVTP,PROCDATE,DEAL_ID,SUBDEALID,EVT_ID,PMT_REF,FCHNG,PRFCNTR,NRT)
select PD_SEQ.nextval,POD,VALD,?,?,CCY,AMNT,AMNTBC,PBR,PDRF,CPDRF,'0',FINALETRS,PNAR,CTYPE,PCID,PREF,DPMT,FLEX_EVENT_CODE,
                 RNARLNG,RNARSHT,OREF,DOCN,OREF_SRC,OPERATOR,OPER_DEPT,AUTHORIZER,AUTH_DEPT,GLO_REF,EVTP,PROCDATE,DEAL_ID,SUBDEALID,EVT_ID,PMT_REF,FCHNG,PRFCNTR,NRT
from PST where id in ($id_invisible$)