-- получаем статистику по очередям
SELECT U.NAME QUEUE_NAME, A.*
  FROM V$AQ A,
       (SELECT QID, NAME FROM USER_QUEUES WHERE NAME IN
          (GLAQ_PKG_CONST.GET_BALANCE_QUEUE_NAME, GLAQ_PKG_CONST.GET_BALANCE_EXC_QUEUE_NAME)
       ) U
 WHERE A.QID = U.QID