SELECT MIN(POD) MIN_POD, ACID, BSAACID
  FROM (
    SELECT T.POD, COALESCE(R.ACID,T.ACID) ACID, COALESCE(R.BSAACID,T.BSAACID) BSAACID
      FROM GL_PDJCHG T
      LEFT JOIN PD R ON R.ID = T.ID
     WHERE T.OPERDAY = ?
       AND (R.INVISIBLE ='1' OR R.INVISIBLE IS NULL)
) V
GROUP BY ACID, BSAACID
