SELECT SUM(
         CASE WHEN P.AMNTBC < 0 THEN P.AMNT ELSE 0 END
       ) DTAC
       , SUM(
         CASE WHEN P.AMNTBC < 0 THEN P.AMNTBC ELSE 0 END
       ) DTBC
       , SUM(
         CASE WHEN P.AMNTBC > 0 THEN P.AMNT ELSE 0 END
       ) CTAC
       , SUM(
         CASE WHEN P.AMNTBC > 0 THEN P.AMNTBC ELSE 0 END
       ) CTBC,
       P.POD, P.BSAACID, P.ACID
  FROM GL_PD P
 WHERE P.BSAACID = ?
 GROUP BY P.POD, P.BSAACID, P.ACID