INSERT INTO GL_PD_H
(
    ID
    , POD
    , VALD
    , ACID
    , BSAACID
    , CCY
    , AMNT
    , AMNTBC
    , AMNTUC
    , PBR
    , PDRF
    , CPDRF
    , INVISIBLE
    , FINALETRS
    , LASTD
    , STATUS
    , ASOC
    , PNAR
    , CTYPE
    , PCID
    , PREF
    , DLID
    , DLTYPE
    , DPMT
    , FLEX_EVENT_CODE
    , RNARLNG
    , RNARSHT
    , OREF
    , DOCN
    , OREF_SRC
    , OPERATOR
    , OPER_DEPT
    , AUTHORIZER
    , AUTH_DEPT
    , GLO_REF
    , EVTP
    , PROCDATE
    , DEAL_ID
    , SUBDEALID
    , MO_NO
    , AN_IND
    , BO_IND
    , POST_TYPE
    , PD_ID
    , STRN_PCID
    , UNLOAD_DAT
)
SELECT   P.ID
       , P.POD
       , P.VALD
       , P.ACID
       , P.BSAACID
       , P.CCY
       , P.AMNT
       , P.AMNTBC
       , P.AMNTUC
       , P.PBR
       , P.PDRF
       , P.CPDRF
       , P.INVISIBLE
       , P.FINALETRS
       , P.LASTD
       , P.STATUS
       , P.ASOC
       , P.PNAR
       , P.CTYPE
       , P.PCID
       , P.PREF
       , P.DLID
       , P.DLTYPE
       , P.DPMT
       , P.FLEX_EVENT_CODE
       , P.RNARLNG
       , P.RNARSHT
       , P.OREF
       , P.DOCN
       , P.OREF_SRC
       , P.OPERATOR
       , P.OPER_DEPT
       , P.AUTHORIZER
       , P.AUTH_DEPT
       , P.GLO_REF
       , P.EVTP
       , P.PROCDATE
       , P.DEAL_ID
       , P.SUBDEALID
       , P.MO_NO
       , P.AN_IND
       , P.BO_IND
       , P.POST_TYPE
       , P.PD_ID
       , P.STRN_PCID
       , S.DAT
  FROM GL_PD P, (SELECT DAT FROM SESSION.GL_TMP_CURRDAY) S
 WHERE P.PD_ID IS NOT NULL