DECLARE
  PRAGMA AUTONOMOUS_TRANSACTION;
  A_SEQ VARCHAR2(30) := ?;
  A_TARGET_VAL VARCHAR2(22) := ?;
  A_TMPINCR NUMBER(22) := 0;
BEGIN
  A_TMPINCR := A_TARGET_VAL - PD_SEQ.NEXTVAL;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE '||A_SEQ||' INCREMENT BY '||TO_CHAR(A_TMPINCR)||' MINVALUE 0';
  A_TMPINCR := PD_SEQ.NEXTVAL;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE '||A_SEQ||' INCREMENT BY 1 MINVALUE 0';
  A_TMPINCR := PD_SEQ.NEXTVAL;
  COMMIT;
END;