DECLARE
      PRAGMA AUTONOMOUS_TRANSACTION;
      A_SEQ VARCHAR2(30) := ?;
      A_TARGET_VAL VARCHAR2(22) := ?;
      A_TMPINCR NUMBER(22) := 0;
BEGIN
    EXECUTE IMMEDIATE 'SELECT TO_NUMBER(:1) - '||A_SEQ||'.NEXTVAL FROM DUAL' INTO A_TMPINCR USING A_TARGET_VAL ;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE '||A_SEQ||' INCREMENT BY '||TO_CHAR(A_TMPINCR)||' MINVALUE 0';
    EXECUTE IMMEDIATE 'SELECT '||A_SEQ||'.NEXTVAL FROM DUAL' INTO A_TMPINCR;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE '||A_SEQ||' INCREMENT BY 1 MINVALUE 0';
    COMMIT;
END;