DECLARE
    PRAGMA AUTONOMOUS_TRANSACTION;
    A_TRIGGER_NAME VARCHAR2(30) := ?;
    A_STATUS CHAR(1) := ?;
BEGIN
    EXECUTE IMMEDIATE 'ALTER TRIGGER '||A_TRIGGER_NAME||CASE WHEN A_STATUS = '1' THEN ' ENABLE' ELSE ' DISABLE' END;
    COMMIT;
END;